---
name: cs610s2020_project05
break: true
fastfail: false
indent: 4
---
writing:
    senior_thesis_status_update.md:
        ConfirmFileExists
        CountFileWords --count 200
        MatchFileFragment --fragment "Your name" --count 0 --exact
        MatchFileFragment --fragment "TODO" --count 0 --exact
        MatchFileFragment --fragment "Item1" --count 0 --exact
        MatchFileFragment --fragment "Item2" --count 0 --exact
        MatchFileFragment --fragment "Item3" --count 0 --exact
        CountMarkdownTags --tag "heading" --count 6 --exact
        CountMarkdownTags --tag "list" --count 1 --exact
CountCommits --count 3
